// ============================================================================
// EnrollChecklist — the enroll picture, rendered identically on both screens.
//
// One renderer, two hosts: MDM tab-1 and the public /mdm-enroll token page.
// Branch A watching tab-1 talks the link holder through the wipe over the phone;
// if the two screens word things differently the call goes in circles. So the
// component is PRESENTATIONAL — it takes an EnrollView and callbacks, and owns
// no query, no auth, no asset id.
//
// ⛔ THERE IS NO `audience` PROP ANY MORE, and nothing here may branch on who is
//    looking. The original contract gave the token page a reduced subset (5 of 7
//    steps, softer PREPARE_FAILED wording, no lock button); the owner overruled
//    it on 2026-08-17 — the link holder is staff at another branch on the SAME
//    ABM, so they can do everything tab-1 can, including scanning the device
//    into ABM. Every re-introduced branch is a way for the two screens to
//    disagree, which is the failure this component exists to prevent.
// ============================================================================

import type { ReactNode } from 'react';
import { useTranslation } from 'react-i18next';
import { Button, Badge } from 'tsp-form';
import {
  Fingerprint, ScanLine, Send, RotateCcw, Smartphone, CheckCircle,
  Loader2, XCircle, HelpCircle, ShieldCheck, CircleDashed, PackageCheck,
  PackageOpen,
} from 'lucide-react';
import { enrollDoneCount, waitStage, type EnrollView } from './enrollView';
import { useTicker, secondsSince, splitDuration } from './useTicker';
import { StepRow, type StepStatus } from './StepRow';

// ── Step model ──────────────────────────────────────────────────────────────

const STEPS_1_5 = [
  { key: 'serial', icon: Fingerprint, where: 'system' },
  { key: 'scan', icon: ScanLine, where: 'device' },
  { key: 'send', icon: Send, where: 'system' },
  { key: 'wipe', icon: RotateCcw, where: 'device' },
  { key: 'enrolled', icon: Smartphone, where: 'auto' },
] as const;

// ── The two-key banner ──────────────────────────────────────────────────────
// 🍎 pull key  — pulled FROM Apple, expires 15 days after enroll. Unlocks the
//                customer's iCloud when we repossess.
// 🏢 push key  — generated by us, pushed INTO the device, never expires. It is
//                what makes a WIPED device unusable without our code.
//
// One banner rather than three separate lines, because the question staff
// actually ask is "can I hand this over?" — and that is answered by the pair
// together plus lock_ready, not by any single row. A device with the Apple key
// and no org key reads reassuring on every other field, and one shipped to a
// real customer on 2026-08-11 for exactly that reason.
//
// ⛔ lock_ready is DB-owned. Never recompute it as has_pull_key && has_push_key.

type KeyState = 'ok' | 'pending' | 'missing' | 'unknown';

function keyChip(state: KeyState, label: string, glyph: string) {
  const map: Record<KeyState, { color: 'success' | 'warning' | 'danger' | 'default'; icon: ReactNode }> = {
    ok: { color: 'success', icon: <ShieldCheck size={12} /> },
    pending: { color: 'warning', icon: <CircleDashed size={12} className="motion-safe:animate-spin" /> },
    missing: { color: 'danger', icon: <XCircle size={12} /> },
    unknown: { color: 'default', icon: <HelpCircle size={12} /> },
  };
  const { color, icon } = map[state];
  return (
    <Badge color={color} startIcon={icon}>
      <span className="mr-1" aria-hidden>{glyph}</span>{label}
    </Badge>
  );
}

export function KeyBanner({ view }: { view: EnrollView }) {
  const { t } = useTranslation();

  const pull: KeyState = !view.in_mdm ? 'unknown' : view.has_pull_key ? 'ok' : 'missing';
  // THREE states, not two: holding the key is not the same as Apple confirming
  // it landed. Only the third protects the device. It arrives 30s–6min after
  // supervision (vs 1–3s for the Apple key), so 🍎 ok / 🏢 pending is the normal
  // shape of a freshly-enrolled device — and it is NOT safe to hand over yet.
  const push: KeyState = !view.in_mdm ? 'unknown'
    : !view.has_push_key ? 'missing'
      : !view.push_key_applied_at ? 'pending' : 'ok';

  const tone = view.lock_ready ? 'alert alert-success' : 'alert alert-warning';

  return (
    <div className={tone}>
      {view.lock_ready ? <PackageCheck size={20} className="shrink-0" /> : <PackageOpen size={20} className="shrink-0" />}
      <div className="min-w-0 flex-1">
        <div className="alert-title">
          {view.lock_ready ? t('asset.mdm.keys.readyTitle') : t('asset.mdm.keys.notReadyTitle')}
        </div>
        <div className="flex items-center gap-2 flex-wrap mt-1.5">
          {keyChip(pull, t('asset.mdm.keys.appleShort'), '🍎')}
          {keyChip(push, t('asset.mdm.keys.orgShort'), '🏢')}
        </div>
        {/* The verdict in words + what to do. Only meaningful once enrolled —
            before that both keys legitimately read "not enrolled". */}
        {view.in_mdm && !view.lock_ready && view.lock_verdict_code && (
          <div className="alert-description mt-1.5">
            {t(`asset.mdm.lockVerdict.${view.lock_verdict_code}`)}
          </div>
        )}
      </div>
    </div>
  );
}

// ── The status band ─────────────────────────────────────────────────────────

type BandTone = 'neutral' | 'info' | 'warning' | 'danger' | 'success';

const BAND_CLASS: Record<BandTone, string> = {
  neutral: 'alert alert-info',
  info: 'alert alert-info',
  warning: 'alert alert-warning',
  danger: 'alert alert-danger',
  success: 'alert alert-success',
};

/**
 * The headline state. `PROFILE_READY` is deliberately an INSTRUCTION, not a
 * status: the system finished its half in ~10 seconds and is now waiting on a
 * PERSON to wipe the device. 134 §5.1 bans a spinner here outright — a spinner
 * says "we're working on it", and staff sit watching it instead of going and
 * wiping the handset, which is the one thing that would move the flow forward.
 */
function bandFor(view: EnrollView): {
  key: string; tone: BandTone; spin: boolean; instruction: boolean;
} {
  // A re-enroll keeps mdm_status at IN_MDM (the view checks the binding first),
  // so the "go wipe it" signal lives in prepare_status.
  if (view.prepare_is_reenroll && view.prepare_status === 'READY') {
    return { key: 'REENROLL_READY', tone: 'warning', spin: false, instruction: true };
  }
  switch (view.mdm_status) {
    case 'NO_SERIAL': return { key: 'NO_SERIAL', tone: 'neutral', spin: false, instruction: false };
    case 'NOT_STARTED': return { key: 'NOT_STARTED', tone: 'neutral', spin: false, instruction: false };
    case 'PREPARING': return { key: 'PREPARING', tone: 'info', spin: true, instruction: false };
    case 'PROFILE_READY': return { key: 'PROFILE_READY', tone: 'warning', spin: false, instruction: true };
    // ⛔ ONE wording for both screens. There used to be a PREPARE_FAILED_REMOTE
    //    variant reading "contact branch A", on the belief that the link holder
    //    had no ABM access. They do — same ABM, they just don't use NNF — so the
    //    dead end was fictional and the real instruction (scan it into ABM,
    //    pick MDM server NNF-MDM-1) applies to them too.
    case 'PREPARE_FAILED': return { key: 'PREPARE_FAILED', tone: 'danger', spin: false, instruction: false };
    case 'IN_MDM': return { key: 'IN_MDM', tone: 'success', spin: false, instruction: false };
    default: return { key: 'NOT_STARTED', tone: 'neutral', spin: false, instruction: false };
  }
}

/** The numbered iOS path, so nobody has to be talked through it by phone. */
function WipeInstructions() {
  const { t } = useTranslation();
  return (
    <ol className="mt-2 flex flex-col gap-1 text-sm list-decimal pl-4">
      <li>{t('asset.mdm.wipeSteps.s1')}</li>
      <li>{t('asset.mdm.wipeSteps.s2')}</li>
      <li>{t('asset.mdm.wipeSteps.s3')}</li>
    </ol>
  );
}

// ── The component ───────────────────────────────────────────────────────────

export interface EnrollChecklistProps {
  view: EnrollView;
  /** Host owns the RPC; this component only asks. Omit to hide the button. */
  onPrepare?: () => void;
  preparing?: boolean;
  /** Already-translated submit error. */
  errorMessage?: string | null;
  /** Rendered inside step 3, under the serial (tab-1 puts its zoom button here). */
  serialSlot?: ReactNode;
  /** Steps 6 and 7 — <EnrollReadinessSteps>, wired to the host's RPC. */
  children?: ReactNode;
  /** Hide the key banner (a host that shows the same information elsewhere). */
  hideKeyBanner?: boolean;
  /** Raw BE reason under a failed prepare. Engineer-facing English, so tab-1
   *  shows it and the token page does not — a presentation choice the host
   *  makes, not a divergence in what the flow MEANS. */
  showRawBlockedReason?: boolean;
}

export function EnrollChecklist({
  view, onPrepare, preparing = false, errorMessage,
  serialSlot, children, hideKeyBanner = false, showRawBlockedReason = false,
}: EnrollChecklistProps) {
  const { t } = useTranslation();

  const band = bandFor(view);
  const doneEnroll = enrollDoneCount(view);

  // Waiting for a human to wipe: the profile is pushed and the device hasn't
  // reported in. Deliberately NOT tied to a local "I just pressed it" flag — the
  // person who needs the check-the-serial hint is usually the one coming back an
  // hour later, whose local state is long gone.
  const awaitingErase = view.prepare_status === 'READY' && !view.in_mdm;
  const stage = awaitingErase ? waitStage(view.prepare_requested_at) : 'FRESH';

  // Tick while waiting so the elapsed time ages on screen between polls.
  useTicker(awaitingErase);
  const waited = awaitingErase ? secondsSince(view.prepare_requested_at) : null;

  const showPrepareButton = view.can_prepare && view.may_prepare && !!onPrepare;
  const isRetry = view.mdm_status === 'PREPARE_FAILED';

  return (
    <div className="flex flex-col gap-4">
      {/* Status band — the headline answer. */}
      <div className={BAND_CLASS[band.tone]}>
        {band.spin
          ? <Loader2 size={20} className="shrink-0 motion-safe:animate-spin" />
          : band.instruction
            ? <RotateCcw size={20} className="shrink-0" />
            : band.tone === 'success'
              ? <CheckCircle size={20} className="shrink-0" />
              : band.tone === 'danger'
                ? <XCircle size={20} className="shrink-0" />
                : <Smartphone size={20} className="shrink-0" />}
        <div className="min-w-0 flex-1">
          <div className="alert-title">{t(`asset.mdm.band.${band.key}.title`)}</div>
          <div className="alert-description">{t(`asset.mdm.band.${band.key}.body`)}</div>

          {/* An instruction state gets the literal steps, not a progress mood. */}
          {band.instruction && <WipeInstructions />}

          {showRawBlockedReason && view.mdm_status === 'PREPARE_FAILED' && view.prepare_blocked_reason && (
            <div className="alert-description font-mono break-words mt-1">{view.prepare_blocked_reason}</div>
          )}

          {/* Elapsed wait, ticking. Presence of a live number is what tells the
              viewer the page is attending to the device, not frozen. */}
          {waited != null && waited >= 30 && (
            <div className="alert-description mt-1 tabular-nums">
              {t('asset.mdm.waitHint.waiting', { time: formatWait(waited) })}
            </div>
          )}
        </div>
      </div>

      {/* Escalating hint — only once the wait is long enough to be worth
          questioning. Info tone, not warning: a long wait is still a valid wait
          and the device may yet arrive on its own. */}
      {stage !== 'FRESH' && (
        <div className="alert alert-info">
          <HelpCircle size={20} className="shrink-0" />
          <div className="min-w-0">
            <div className="alert-title">{t(`asset.mdm.waitHint.${stage}.title`)}</div>
            <div className="alert-description">{t(`asset.mdm.waitHint.${stage}.body`)}</div>
          </div>
        </div>
      )}

      {errorMessage && (
        <div className="alert alert-danger">
          <XCircle size={16} className="shrink-0" />
          <span className="min-w-0">{errorMessage}</span>
        </div>
      )}

      {!hideKeyBanner && view.in_mdm && <KeyBanner view={view} />}

      {/* The checklist itself. */}
      <div className="border border-line rounded-md p-4">
        <div className="flex flex-col">
          {STEPS_1_5.map((step, i) => {
            const state: StepStatus = i < doneEnroll ? 'done' : (i === doneEnroll ? 'current' : 'todo');
            const isSendStep = step.key === 'send';
            return (
              <StepRow
                key={step.key}
                n={i + 1}
                icon={step.icon}
                title={t(`asset.mdm.step.${step.key}`)}
                where={t(`asset.mdm.stepWhere.${step.where}`)}
                state={state}
                last={!children && i === STEPS_1_5.length - 1}
              >
                {isSendStep && serialSlot}

                {isSendStep && showPrepareButton && (
                  <div className="flex flex-col gap-1.5">
                    <div>
                      <Button
                        color="primary"
                        size="sm"
                        startIcon={isRetry || view.prepare_is_reenroll
                          ? <RotateCcw size={15} />
                          : <Send size={15} />}
                        onClick={onPrepare}
                        disabled={preparing}
                      >
                        {isRetry
                          ? t('asset.mdm.button.retry')
                          : view.prepare_is_reenroll
                            ? t('asset.mdm.button.reenroll')
                            : t('asset.mdm.button.prepare')}
                      </Button>
                    </div>
                    {view.prepare_is_reenroll && !isRetry && (
                      <p className="text-xs text-subtle">{t('asset.mdm.button.reenrollHint')}</p>
                    )}
                  </div>
                )}
                {isSendStep && view.can_prepare && !view.may_prepare && (
                  <div className="text-xs text-subtler">{t('asset.mdm.noPermission')}</div>
                )}
              </StepRow>
            );
          })}
          {children}
        </div>
      </div>
    </div>
  );
}

/** "4:12" under an hour, "1:04:12" past it. Digits only — nothing to translate. */
function formatWait(seconds: number): string {
  const { h, m, s } = splitDuration(seconds);
  const mm = String(m).padStart(2, '0');
  const ss = String(s).padStart(2, '0');
  return h > 0 ? `${h}:${mm}:${ss}` : `${m}:${ss}`;
}
