// Build-time bake: pull EN + TH search keywords from emojibase-data (CLDR data)
// for exactly the emojis in our curated layout, and regenerate
// src/pages/chat/emojiKeywords.generated.ts.
//
// Run: node scripts/bakeEmojiKeywords.mjs
// Re-run whenever EMOJI_LAYOUT in src/pages/chat/emojiData.ts changes.
//
// Why build-time: keeps the ~2MB emojibase data out of the app bundle. We ship
// only the keyword arrays for the ~120 emojis we actually render.

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import { createRequire } from 'node:module';

const require = createRequire(import.meta.url);
const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');

const enData = require('emojibase-data/en/data.json');
const thData = require('emojibase-data/th/data.json');

// Normalize away the FE0F / FE0E variation selectors so our literals (which
// often omit FE0F) match emojibase entries (which include it).
const norm = (s) => s.replace(/[️︎]/g, '');

// Index emojibase by normalized char. Keep the first entry per key.
const byChar = new Map();
for (const e of enData) {
  const k = norm(e.emoji);
  byChar.set(k, { ...(byChar.get(k) ?? {}), en: e });
}
for (const e of thData) {
  const k = norm(e.emoji);
  byChar.set(k, { ...(byChar.get(k) ?? {}), th: e });
}

// Extract the curated char list from emojiData.ts without importing TS:
// pull every quoted token inside `chars: [ … ]` blocks, in source order.
const dataSrc = readFileSync(resolve(ROOT, 'src/pages/chat/emojiData.ts'), 'utf8');
const chars = [];
for (const block of dataSrc.matchAll(/chars:\s*\[([\s\S]*?)\]/g)) {
  for (const m of block[1].matchAll(/'([^']+)'/g)) chars.push(m[1]);
}

const missing = [];
const map = {};
for (const ch of chars) {
  const slot = byChar.get(norm(ch));
  if (!slot) { missing.push(ch); continue; }
  const terms = new Set();
  for (const src of [slot.en, slot.th]) {
    if (!src) continue;
    if (src.label) terms.add(src.label.toLowerCase());
    for (const tag of src.tags ?? []) terms.add(String(tag).toLowerCase());
  }
  map[ch] = [...terms];
}

if (missing.length) {
  console.warn(`[bake-emoji] ${missing.length} char(s) not found in emojibase, no keywords baked:`, missing.join(' '));
}

const banner = `// AUTO-GENERATED by scripts/bakeEmojiKeywords.mjs — DO NOT EDIT BY HAND.
// EN + TH search keywords (Unicode CLDR via emojibase-data) for the curated
// chat emoji set. Re-run \`node scripts/bakeEmojiKeywords.mjs\` after editing
// EMOJI_LAYOUT in emojiData.ts.

export const EMOJI_KEYWORDS: Record<string, string[]> = ${JSON.stringify(map, null, 2)};
`;

const outPath = resolve(ROOT, 'src/pages/chat/emojiKeywords.generated.ts');
writeFileSync(outPath, banner, 'utf8');
console.log(`[bake-emoji] wrote ${Object.keys(map).length} emoji keyword sets → ${outPath}`);
